version: "3.8"

services:
  postgres:
    image: postgres:13.1
    container_name: postgres_cqrs_saga
    environment:
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: ordersdb, paymentsdb, shipmentsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_vol:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  axon-server:
      image: axoniq/axonserver:latest-jdk-17-dev
      ports:
        - "8024:8024"
        - "8124:8124"
      environment:
        axoniq_axonserver_hostname: axon-server
        axoniq_axonserver_autocluster_first: axon-server
        axoniq_axonserver_autocluster_contexts: _admin,default

      volumes:
        - axon_data_vol:/axonserver/data
        - axon_events_vol:/axonserver/events


volumes:
  postgres_data_vol:
    driver: local
  axon_data_vol:
    driver: local
  axon_events_vol:
    driver: local