server:
  port: 7171
  servlet:
    context-path: /api/ms-order/v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST_URL:localhost}:${EUREKA_PORT:3999}/eureka

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ordersdb}?useSSL=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Prasanna@123}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

    database-platform: com.ab.saga.orderservice.infrastructure.hibernate.NoToastPostgresSQLDialect

axon:
  axonserver:
    enabled: true
    context: default
    component-name: order-service
    servers: localhost:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson